id: P2B731154
initial_creation_type: ebook
source_metadata:
  title: Cool Doc Title
  subtitle: Cool SubTitle
  authors:
  - Guy Cool
  collection: Cool Collection
  publisher: Cool Publisher
  id: '8675309'
  cover: tmp82aedjgh.png
  credit: tmpmd4stz2_.png
created_at: '2022-04-29T14:11:40.337989'
last_modified_at: '2022-04-29T14:11:40.339432'
